"""
Generated by restcodegen (https://github.com/ValeriyMenshikov/restcodegen).

    source: {{ service_name|to_snake_case }}
    version: {{ version }}

    Do not edit the class manually.
"""

from __future__ import annotations

from typing import Any
from uuid import UUID

from pydantic import BaseModel, EmailStr, Field, RootModel, SecretStr


class BearerResponse(BaseModel):
    access_token: str = Field(..., title="Access Token")
    token_type: str = Field(..., title="Token Type")


class GrantType(RootModel[str]):
    root: str = Field(..., pattern="^password$", title="Grant Type")


class BodyAuthJwtLoginApiAuthJwtLoginPost(BaseModel):
    grant_type: GrantType | None = Field(None, title="Grant Type")
    username: str = Field(..., title="Username")
    password: SecretStr = Field(..., title="Password")
    scope: str | None = Field("", title="Scope")
    client_id: str | None = Field(None, title="Client Id")
    client_secret: SecretStr | None = Field(None, title="Client Secret")


class BodyResetForgotPasswordApiAuthForgotPasswordPost(BaseModel):
    email: EmailStr = Field(..., title="Email")


class BodyResetResetPasswordApiAuthResetPasswordPost(BaseModel):
    token: str = Field(..., title="Token")
    password: str = Field(..., title="Password")


class BodyVerifyRequestTokenApiAuthRequestVerifyTokenPost(BaseModel):
    email: EmailStr = Field(..., title="Email")


class BodyVerifyVerifyApiAuthVerifyPost(BaseModel):
    token: str = Field(..., title="Token")


class DummyModelDTO(BaseModel):
    id: int = Field(..., title="Id")
    name: str = Field(..., title="Name")


class DummyModelInputDTO(BaseModel):
    name: str = Field(..., title="Name")


class ErrorModel(BaseModel):
    detail: str | dict[str, str] = Field(..., title="Detail")


class Message(BaseModel):
    message: str = Field(..., title="Message")


class RMQMessageDTO(BaseModel):
    exchange_name: str = Field(..., title="Exchange Name")
    routing_key: str = Field(..., title="Routing Key")
    message: str = Field(..., title="Message")


class UserCreate(BaseModel):
    email: EmailStr = Field(..., title="Email")
    password: str = Field(..., title="Password")
    is_active: bool | None = Field(True, title="Is Active")
    is_superuser: bool | None = Field(False, title="Is Superuser")
    is_verified: bool | None = Field(False, title="Is Verified")


class UserRead(BaseModel):
    id: UUID = Field(..., title="Id")
    email: EmailStr = Field(..., title="Email")
    is_active: bool | None = Field(True, title="Is Active")
    is_superuser: bool | None = Field(False, title="Is Superuser")
    is_verified: bool | None = Field(False, title="Is Verified")


class UserUpdate(BaseModel):
    password: str | None = Field(None, title="Password")
    email: EmailStr | None = Field(None, title="Email")
    is_active: bool | None = Field(None, title="Is Active")
    is_superuser: bool | None = Field(None, title="Is Superuser")
    is_verified: bool | None = Field(None, title="Is Verified")


class HealthCheckApiHealthGetResponse200(RootModel[Any]):
    root: Any


class ResetForgotPasswordApiAuthForgotPasswordPostResponse202(RootModel[Any]):
    root: Any


class ResetResetPasswordApiAuthResetPasswordPostResponse200(RootModel[Any]):
    root: Any


class VerifyRequestTokenApiAuthRequestVerifyTokenPostResponse202(RootModel[Any]):
    root: Any


class AuthJwtLogoutApiAuthJwtLogoutPostResponse200(RootModel[Any]):
    root: Any


class GetDummyModelsApiDummyGetResponse200(RootModel[list[DummyModelDTO]]):
    root: list[DummyModelDTO] = Field(
        ..., title="Response Get Dummy Models Api Dummy  Get"
    )


class CreateDummyModelApiDummyPutResponse200(RootModel[Any]):
    root: Any


class SendRabbitMessageApiRabbitPostResponse200(RootModel[Any]):
    root: Any


class ValidationErrorLocItem(RootModel[str | int]):
    root: str | int


class ValidationError(BaseModel):
    loc: list[ValidationErrorLocItem] = Field(..., title="Location")
    msg: str = Field(..., title="Message")
    type: str = Field(..., title="Error Type")


class HTTPValidationError(BaseModel):
    detail: list[ValidationError] | None = Field(None, title="Detail")
