"""
Generated by restcodegen (https://github.com/ValeriyMenshikov/restcodegen).

    source: todo
    version: 2.0.1

    Do not edit the class manually.
"""

from typing import Any

from httpx import Client, Response

from clients.http.todo.models.api_models import (
    AuthJwtLogoutApiAuthJwtLogoutPostResponse200,
    BearerResponse,
    BodyAuthJwtLoginApiAuthJwtLoginPost,
    BodyResetForgotPasswordApiAuthForgotPasswordPost,
    BodyResetResetPasswordApiAuthResetPasswordPost,
    BodyVerifyRequestTokenApiAuthRequestVerifyTokenPost,
    BodyVerifyVerifyApiAuthVerifyPost,
    ResetForgotPasswordApiAuthForgotPasswordPostResponse202,
    ResetResetPasswordApiAuthResetPasswordPostResponse200,
    UserCreate,
    UserRead,
    VerifyRequestTokenApiAuthRequestVerifyTokenPostResponse202,
)


class AuthApi:
    def __init__(self, api_client: Client) -> None:
        self.api_client = api_client

    def post_api_auth_register(
        self,
        user_create: UserCreate,
        **kwargs: Any,
    ) -> UserRead:
        """
        Register:Register.

        Args:
            user_create(UserCreate): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            UserRead: ...
        """  # noqa: E501

        response = self.post_api_auth_register_with_http_info(
            user_create=user_create,
            **kwargs,
        )
        return UserRead.model_validate_json(response.text)

    def post_api_auth_register_with_http_info(
        self,
        user_create: UserCreate,
        **kwargs: Any,
    ) -> Response:
        """
        Register:Register.

        Args:
            user_create(UserCreate): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Response: ...
        """  # noqa: E501
        headers = kwargs.pop("headers", {})

        content = user_create.model_dump_json(exclude_none=True, by_alias=True)
        headers.update({"Content-Type": "application/json"})
        response = self.api_client.post(
            url="/api/auth/register",
            content=content,
            headers=headers,
            **kwargs,
        )
        return response

    def post_api_auth_forgot_password(
        self,
        body_reset_forgot_password_api_auth_forgot_password_post: BodyResetForgotPasswordApiAuthForgotPasswordPost,  # noqa: E501
        **kwargs: Any,
    ) -> ResetForgotPasswordApiAuthForgotPasswordPostResponse202:
        """
        Reset:Forgot Password.

        Args:
            body_reset_forgot_password_api_auth_forgot_password_post(BodyResetForgotPasswordApiAuthForgotPasswordPost): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            ResetForgotPasswordApiAuthForgotPasswordPostResponse202: ...
        """  # noqa: E501

        response = self.post_api_auth_forgot_password_with_http_info(
            body_reset_forgot_password_api_auth_forgot_password_post=body_reset_forgot_password_api_auth_forgot_password_post,
            **kwargs,
        )
        return (
            ResetForgotPasswordApiAuthForgotPasswordPostResponse202.model_validate_json(
                response.text
            )
        )

    def post_api_auth_forgot_password_with_http_info(
        self,
        body_reset_forgot_password_api_auth_forgot_password_post: BodyResetForgotPasswordApiAuthForgotPasswordPost,  # noqa: E501
        **kwargs: Any,
    ) -> Response:
        """
        Reset:Forgot Password.

        Args:
            body_reset_forgot_password_api_auth_forgot_password_post(BodyResetForgotPasswordApiAuthForgotPasswordPost): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Response: ...
        """  # noqa: E501
        headers = kwargs.pop("headers", {})

        content = (
            body_reset_forgot_password_api_auth_forgot_password_post.model_dump_json(
                exclude_none=True, by_alias=True
            )
        )
        headers.update({"Content-Type": "application/json"})
        response = self.api_client.post(
            url="/api/auth/forgot-password",
            content=content,
            headers=headers,
            **kwargs,
        )
        return response

    def post_api_auth_reset_password(
        self,
        body_reset_reset_password_api_auth_reset_password_post: BodyResetResetPasswordApiAuthResetPasswordPost,  # noqa: E501
        **kwargs: Any,
    ) -> ResetResetPasswordApiAuthResetPasswordPostResponse200:
        """
        Reset:Reset Password.

        Args:
            body_reset_reset_password_api_auth_reset_password_post(BodyResetResetPasswordApiAuthResetPasswordPost): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            ResetResetPasswordApiAuthResetPasswordPostResponse200: ...
        """  # noqa: E501

        response = self.post_api_auth_reset_password_with_http_info(
            body_reset_reset_password_api_auth_reset_password_post=body_reset_reset_password_api_auth_reset_password_post,
            **kwargs,
        )
        return (
            ResetResetPasswordApiAuthResetPasswordPostResponse200.model_validate_json(
                response.text
            )
        )

    def post_api_auth_reset_password_with_http_info(
        self,
        body_reset_reset_password_api_auth_reset_password_post: BodyResetResetPasswordApiAuthResetPasswordPost,  # noqa: E501
        **kwargs: Any,
    ) -> Response:
        """
        Reset:Reset Password.

        Args:
            body_reset_reset_password_api_auth_reset_password_post(BodyResetResetPasswordApiAuthResetPasswordPost): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Response: ...
        """  # noqa: E501
        headers = kwargs.pop("headers", {})

        content = (
            body_reset_reset_password_api_auth_reset_password_post.model_dump_json(
                exclude_none=True, by_alias=True
            )
        )
        headers.update({"Content-Type": "application/json"})
        response = self.api_client.post(
            url="/api/auth/reset-password",
            content=content,
            headers=headers,
            **kwargs,
        )
        return response

    def post_api_auth_request_verify_token(
        self,
        body_verify_request_token_api_auth_request_verify_token_post: BodyVerifyRequestTokenApiAuthRequestVerifyTokenPost,  # noqa: E501
        **kwargs: Any,
    ) -> VerifyRequestTokenApiAuthRequestVerifyTokenPostResponse202:
        """
        Verify:Request-Token.

        Args:
            body_verify_request_token_api_auth_request_verify_token_post(BodyVerifyRequestTokenApiAuthRequestVerifyTokenPost): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            VerifyRequestTokenApiAuthRequestVerifyTokenPostResponse202: ...
        """  # noqa: E501

        response = self.post_api_auth_request_verify_token_with_http_info(
            body_verify_request_token_api_auth_request_verify_token_post=body_verify_request_token_api_auth_request_verify_token_post,
            **kwargs,
        )
        return VerifyRequestTokenApiAuthRequestVerifyTokenPostResponse202.model_validate_json(
            response.text
        )

    def post_api_auth_request_verify_token_with_http_info(
        self,
        body_verify_request_token_api_auth_request_verify_token_post: BodyVerifyRequestTokenApiAuthRequestVerifyTokenPost,  # noqa: E501
        **kwargs: Any,
    ) -> Response:
        """
        Verify:Request-Token.

        Args:
            body_verify_request_token_api_auth_request_verify_token_post(BodyVerifyRequestTokenApiAuthRequestVerifyTokenPost): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Response: ...
        """  # noqa: E501
        headers = kwargs.pop("headers", {})

        content = body_verify_request_token_api_auth_request_verify_token_post.model_dump_json(
            exclude_none=True, by_alias=True
        )
        headers.update({"Content-Type": "application/json"})
        response = self.api_client.post(
            url="/api/auth/request-verify-token",
            content=content,
            headers=headers,
            **kwargs,
        )
        return response

    def post_api_auth_verify(
        self,
        body_verify_verify_api_auth_verify_post: BodyVerifyVerifyApiAuthVerifyPost,
        **kwargs: Any,
    ) -> UserRead:
        """
        Verify:Verify.

        Args:
            body_verify_verify_api_auth_verify_post(BodyVerifyVerifyApiAuthVerifyPost): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            UserRead: ...
        """  # noqa: E501

        response = self.post_api_auth_verify_with_http_info(
            body_verify_verify_api_auth_verify_post=body_verify_verify_api_auth_verify_post,
            **kwargs,
        )
        return UserRead.model_validate_json(response.text)

    def post_api_auth_verify_with_http_info(
        self,
        body_verify_verify_api_auth_verify_post: BodyVerifyVerifyApiAuthVerifyPost,
        **kwargs: Any,
    ) -> Response:
        """
        Verify:Verify.

        Args:
            body_verify_verify_api_auth_verify_post(BodyVerifyVerifyApiAuthVerifyPost): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Response: ...
        """  # noqa: E501
        headers = kwargs.pop("headers", {})

        content = body_verify_verify_api_auth_verify_post.model_dump_json(
            exclude_none=True, by_alias=True
        )
        headers.update({"Content-Type": "application/json"})
        response = self.api_client.post(
            url="/api/auth/verify",
            content=content,
            headers=headers,
            **kwargs,
        )
        return response

    def post_api_auth_jwt_login(
        self,
        body_auth_jwt_login_api_auth_jwt_login_post: BodyAuthJwtLoginApiAuthJwtLoginPost,  # noqa: E501
        **kwargs: Any,
    ) -> BearerResponse:
        """
        Auth:Jwt.Login.

        Args:
            body_auth_jwt_login_api_auth_jwt_login_post(BodyAuthJwtLoginApiAuthJwtLoginPost): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            BearerResponse: ...
        """  # noqa: E501

        response = self.post_api_auth_jwt_login_with_http_info(
            body_auth_jwt_login_api_auth_jwt_login_post=body_auth_jwt_login_api_auth_jwt_login_post,
            **kwargs,
        )
        return BearerResponse.model_validate_json(response.text)

    def post_api_auth_jwt_login_with_http_info(
        self,
        body_auth_jwt_login_api_auth_jwt_login_post: BodyAuthJwtLoginApiAuthJwtLoginPost,  # noqa: E501
        **kwargs: Any,
    ) -> Response:
        """
        Auth:Jwt.Login.

        Args:
            body_auth_jwt_login_api_auth_jwt_login_post(BodyAuthJwtLoginApiAuthJwtLoginPost): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Response: ...
        """  # noqa: E501
        headers = kwargs.pop("headers", {})

        content = body_auth_jwt_login_api_auth_jwt_login_post.model_dump_json(
            exclude_none=True, by_alias=True
        )
        headers.update({"Content-Type": "application/json"})
        response = self.api_client.post(
            url="/api/auth/jwt/login",
            content=content,
            headers=headers,
            **kwargs,
        )
        return response

    def post_api_auth_jwt_logout(
        self,
        **kwargs: Any,
    ) -> AuthJwtLogoutApiAuthJwtLogoutPostResponse200:
        """
        Auth:Jwt.Logout.

        Args:
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            AuthJwtLogoutApiAuthJwtLogoutPostResponse200: ...
        """  # noqa: E501

        response = self.post_api_auth_jwt_logout_with_http_info(
            **kwargs,
        )
        return AuthJwtLogoutApiAuthJwtLogoutPostResponse200.model_validate_json(
            response.text
        )

    def post_api_auth_jwt_logout_with_http_info(
        self,
        **kwargs: Any,
    ) -> Response:
        """
        Auth:Jwt.Logout.

        Args:
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Response: ...
        """  # noqa: E501
        headers = kwargs.pop("headers", {})

        response = self.api_client.post(
            url="/api/auth/jwt/logout",
            headers=headers,
            **kwargs,
        )
        return response
