"""
Generated by restcodegen (https://github.com/ValeriyMenshikov/restcodegen).

    source: todo
    version: 2.0.1

    Do not edit the class manually.
"""

from typing import Any

from httpx import Client, Response

from clients.http.todo.models.api_models import (
    CreateDummyModelApiDummyPutResponse200,
    DummyModelInputDTO,
    GetDummyModelsApiDummyGetResponse200,
)


class DummyApi:
    def __init__(self, api_client: Client) -> None:
        self.api_client = api_client

    def get_api_dummy(
        self,
        limit: int | None = None,
        offset: int | None = None,
        **kwargs: Any,
    ) -> GetDummyModelsApiDummyGetResponse200:
        """
        Get Dummy Models.

        Args:
            limit(int | None, optional): ...
            offset(int | None, optional): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            GetDummyModelsApiDummyGetResponse200: ...
        """  # noqa: E501

        response = self.get_api_dummy_with_http_info(
            limit=limit,
            offset=offset,
            **kwargs,
        )
        return GetDummyModelsApiDummyGetResponse200.model_validate_json(response.text)

    def get_api_dummy_with_http_info(
        self,
        limit: int | None = None,
        offset: int | None = None,
        **kwargs: Any,
    ) -> Response:
        """
        Get Dummy Models.

        Args:
            limit(int, optional): ...
            offset(int, optional): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Response: ...
        """  # noqa: E501
        # process the query parameters
        params_map = {
            "limit": limit,
            "offset": offset,
        }
        params = {k: v for k, v in params_map.items() if v}
        headers = kwargs.pop("headers", {})

        response = self.api_client.get(
            url="/api/dummy/",
            params=params,
            headers=headers,
            **kwargs,
        )
        return response

    def put_api_dummy(
        self,
        dummy_model_input_dto: DummyModelInputDTO,
        **kwargs: Any,
    ) -> CreateDummyModelApiDummyPutResponse200:
        """
        Create Dummy Model.

        Args:
            dummy_model_input_dto(DummyModelInputDTO): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            CreateDummyModelApiDummyPutResponse200: ...
        """  # noqa: E501

        response = self.put_api_dummy_with_http_info(
            dummy_model_input_dto=dummy_model_input_dto,
            **kwargs,
        )
        return CreateDummyModelApiDummyPutResponse200.model_validate_json(response.text)

    def put_api_dummy_with_http_info(
        self,
        dummy_model_input_dto: DummyModelInputDTO,
        **kwargs: Any,
    ) -> Response:
        """
        Create Dummy Model.

        Args:
            dummy_model_input_dto(DummyModelInputDTO): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Response: ...
        """  # noqa: E501
        headers = kwargs.pop("headers", {})

        content = dummy_model_input_dto.model_dump_json(
            exclude_none=True, by_alias=True
        )
        headers.update({"Content-Type": "application/json"})
        response = self.api_client.put(
            url="/api/dummy/",
            content=content,
            headers=headers,
            **kwargs,
        )
        return response
