"""
Generated by restcodegen (https://github.com/ValeriyMenshikov/restcodegen).

    source: todo
    version: 2.0.1

    Do not edit the class manually.
"""

from typing import Any

from httpx import Client, Response

from clients.http.todo.models.api_models import (
    Message,
)


class EchoApi:
    def __init__(self, api_client: Client) -> None:
        self.api_client = api_client

    def post_api_echo(
        self,
        message: Message,
        **kwargs: Any,
    ) -> Message:
        """
        Send Echo Message.

        Args:
            message(Message): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Message: ...
        """  # noqa: E501

        response = self.post_api_echo_with_http_info(
            message=message,
            **kwargs,
        )
        return Message.model_validate_json(response.text)

    def post_api_echo_with_http_info(
        self,
        message: Message,
        **kwargs: Any,
    ) -> Response:
        """
        Send Echo Message.

        Args:
            message(Message): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Response: ...
        """  # noqa: E501
        headers = kwargs.pop("headers", {})

        content = message.model_dump_json(exclude_none=True, by_alias=True)
        headers.update({"Content-Type": "application/json"})
        response = self.api_client.post(
            url="/api/echo/",
            content=content,
            headers=headers,
            **kwargs,
        )
        return response
