"""
Generated by restcodegen (https://github.com/ValeriyMenshikov/restcodegen).

    source: todo
    version: 2.0.1

    Do not edit the class manually.
"""

from typing import Any

from httpx import Client, Response

from clients.http.todo.models.api_models import (
    RMQMessageDTO,
    SendRabbitMessageApiRabbitPostResponse200,
)


class RabbitApi:
    def __init__(self, api_client: Client) -> None:
        self.api_client = api_client

    def post_api_rabbit(
        self,
        rmq_message_dto: RMQMessageDTO,
        **kwargs: Any,
    ) -> SendRabbitMessageApiRabbitPostResponse200:
        """
        Send Rabbit Message.

        Args:
            rmq_message_dto(RMQMessageDTO): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            SendRabbitMessageApiRabbitPostResponse200: ...
        """  # noqa: E501

        response = self.post_api_rabbit_with_http_info(
            rmq_message_dto=rmq_message_dto,
            **kwargs,
        )
        return SendRabbitMessageApiRabbitPostResponse200.model_validate_json(
            response.text
        )

    def post_api_rabbit_with_http_info(
        self,
        rmq_message_dto: RMQMessageDTO,
        **kwargs: Any,
    ) -> Response:
        """
        Send Rabbit Message.

        Args:
            rmq_message_dto(RMQMessageDTO): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Response: ...
        """  # noqa: E501
        headers = kwargs.pop("headers", {})

        content = rmq_message_dto.model_dump_json(exclude_none=True, by_alias=True)
        headers.update({"Content-Type": "application/json"})
        response = self.api_client.post(
            url="/api/rabbit/",
            content=content,
            headers=headers,
            **kwargs,
        )
        return response
