"""
Generated by restcodegen (https://github.com/ValeriyMenshikov/restcodegen).

    source: todo
    version: 2.0.1

    Do not edit the class manually.
"""

from typing import Any

from httpx import Client, Response

from clients.http.todo.models.api_models import (
    UserRead,
    UserUpdate,
)


class UsersApi:
    def __init__(self, api_client: Client) -> None:
        self.api_client = api_client

    def get_api_users_me(
        self,
        **kwargs: Any,
    ) -> UserRead:
        """
        Users:Current User.

        Args:
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            UserRead: ...
        """  # noqa: E501

        response = self.get_api_users_me_with_http_info(
            **kwargs,
        )
        return UserRead.model_validate_json(response.text)

    def get_api_users_me_with_http_info(
        self,
        **kwargs: Any,
    ) -> Response:
        """
        Users:Current User.

        Args:
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Response: ...
        """  # noqa: E501
        headers = kwargs.pop("headers", {})

        response = self.api_client.get(
            url="/api/users/me",
            headers=headers,
            **kwargs,
        )
        return response

    def patch_api_users_me(
        self,
        user_update: UserUpdate,
        **kwargs: Any,
    ) -> UserRead:
        """
        Users:Patch Current User.

        Args:
            user_update(UserUpdate): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            UserRead: ...
        """  # noqa: E501

        response = self.patch_api_users_me_with_http_info(
            user_update=user_update,
            **kwargs,
        )
        return UserRead.model_validate_json(response.text)

    def patch_api_users_me_with_http_info(
        self,
        user_update: UserUpdate,
        **kwargs: Any,
    ) -> Response:
        """
        Users:Patch Current User.

        Args:
            user_update(UserUpdate): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Response: ...
        """  # noqa: E501
        headers = kwargs.pop("headers", {})

        content = user_update.model_dump_json(exclude_none=True, by_alias=True)
        headers.update({"Content-Type": "application/json"})
        response = self.api_client.patch(
            url="/api/users/me",
            content=content,
            headers=headers,
            **kwargs,
        )
        return response

    def get_api_users_id(
        self,
        id_: str,
        **kwargs: Any,
    ) -> UserRead:
        """
        Users:User.

        Args:
            id_(str, required): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            UserRead: ...
        """  # noqa: E501

        response = self.get_api_users_id_with_http_info(
            id_=id_,
            **kwargs,
        )
        return UserRead.model_validate_json(response.text)

    def get_api_users_id_with_http_info(
        self,
        id_: str,
        **kwargs: Any,
    ) -> Response:
        """
        Users:User.

        Args:
            id_(str, required): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Response: ...
        """  # noqa: E501
        headers = kwargs.pop("headers", {})

        response = self.api_client.get(
            url=f"/api/users/{id_}",
            headers=headers,
            **kwargs,
        )
        return response

    def patch_api_users_id(
        self,
        user_update: UserUpdate,
        id_: str,
        **kwargs: Any,
    ) -> UserRead:
        """
        Users:Patch User.

        Args:
            user_update(UserUpdate): ...
            id_(str, required): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            UserRead: ...
        """  # noqa: E501

        response = self.patch_api_users_id_with_http_info(
            id_=id_,
            user_update=user_update,
            **kwargs,
        )
        return UserRead.model_validate_json(response.text)

    def patch_api_users_id_with_http_info(
        self,
        user_update: UserUpdate,
        id_: str,
        **kwargs: Any,
    ) -> Response:
        """
        Users:Patch User.

        Args:
            user_update(UserUpdate): ...
            id_(str, required): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Response: ...
        """  # noqa: E501
        headers = kwargs.pop("headers", {})

        content = user_update.model_dump_json(exclude_none=True, by_alias=True)
        headers.update({"Content-Type": "application/json"})
        response = self.api_client.patch(
            url=f"/api/users/{id_}",
            content=content,
            headers=headers,
            **kwargs,
        )
        return response

    def delete_api_users_id(
        self,
        id_: str,
        **kwargs: Any,
    ) -> Response:
        """
        Users:Delete User.

        Args:
            id_(str, required): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            None: ...
        """  # noqa: E501

        response = self.delete_api_users_id_with_http_info(
            id_=id_,
            **kwargs,
        )
        return response

    def delete_api_users_id_with_http_info(
        self,
        id_: str,
        **kwargs: Any,
    ) -> Response:
        """
        Users:Delete User.

        Args:
            id_(str, required): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Response: ...
        """  # noqa: E501
        headers = kwargs.pop("headers", {})

        response = self.api_client.delete(
            url=f"/api/users/{id_}",
            headers=headers,
            **kwargs,
        )
        return response
